import MainLayout from "../components/MainLayout/MainLayout";
import { getDictionary } from "../utils/getDictionary";
import { supportedLanguages } from "@/types";
import type { Metadata } from "next";
import { checkAuth } from "../actions/auth";

export const metadata: Metadata = {
  title: "Services App",
  description: "Generated by create next app",
};

type Props = {
  params: {
    lang: supportedLanguages;
  };
};

export default async function Home({ params: { lang } }: Props) {
  const dictionary = await getDictionary(lang);

  // INFO: just an example of getting session info
  const data = await checkAuth();
  console.log(data);

  return (
    <MainLayout lang={lang}>
      <main>{dictionary.header.nav.home}</main>
    </MainLayout>
  );
}
